//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseConnectionDetails) DeepCopyInto(out *DatabaseConnectionDetails) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseConnectionDetails.
func (in *DatabaseConnectionDetails) DeepCopy() *DatabaseConnectionDetails {
	if in == nil {
		return nil
	}
	out := new(DatabaseConnectionDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaintenanceJobStatus) DeepCopyInto(out *MaintenanceJobStatus) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UpgradeModules != nil {
		in, out := &in.UpgradeModules, &out.UpgradeModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaintenanceJobStatus.
func (in *MaintenanceJobStatus) DeepCopy() *MaintenanceJobStatus {
	if in == nil {
		return nil
	}
	out := new(MaintenanceJobStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooConfig) DeepCopyInto(out *OdooConfig) {
	*out = *in
	if in.WithoutDemo != nil {
		in, out := &in.WithoutDemo, &out.WithoutDemo
		*out = new(bool)
		**out = **in
	}
	if in.ProxyMode != nil {
		in, out := &in.ProxyMode, &out.ProxyMode
		*out = new(bool)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = new(int32)
		**out = **in
	}
	if in.MaxCronThreads != nil {
		in, out := &in.MaxCronThreads, &out.MaxCronThreads
		*out = new(int32)
		**out = **in
	}
	if in.ExtraAddonsPaths != nil {
		in, out := &in.ExtraAddonsPaths, &out.ExtraAddonsPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ListDb != nil {
		in, out := &in.ListDb, &out.ListDb
		*out = new(bool)
		**out = **in
	}
	if in.ServerWideModules != nil {
		in, out := &in.ServerWideModules, &out.ServerWideModules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoadLanguages != nil {
		in, out := &in.LoadLanguages, &out.LoadLanguages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ExtraOptions != nil {
		in, out := &in.ExtraOptions, &out.ExtraOptions
		*out = make(map[string]OdooOptionValue, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooConfig.
func (in *OdooConfig) DeepCopy() *OdooConfig {
	if in == nil {
		return nil
	}
	out := new(OdooConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDatabaseConfig) DeepCopyInto(out *OdooDatabaseConfig) {
	*out = *in
	in.HostFromSecret.DeepCopyInto(&out.HostFromSecret)
	in.PortFromSecret.DeepCopyInto(&out.PortFromSecret)
	in.UserFromSecret.DeepCopyInto(&out.UserFromSecret)
	in.PasswordFromSecret.DeepCopyInto(&out.PasswordFromSecret)
	in.NameFromSecret.DeepCopyInto(&out.NameFromSecret)
	in.SSLFromSecret.DeepCopyInto(&out.SSLFromSecret)
	in.MaxConnFromSecret.DeepCopyInto(&out.MaxConnFromSecret)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDatabaseConfig.
func (in *OdooDatabaseConfig) DeepCopy() *OdooDatabaseConfig {
	if in == nil {
		return nil
	}
	out := new(OdooDatabaseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDatabaseStatus) DeepCopyInto(out *OdooDatabaseStatus) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDatabaseStatus.
func (in *OdooDatabaseStatus) DeepCopy() *OdooDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(OdooDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDeployment) DeepCopyInto(out *OdooDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDeployment.
func (in *OdooDeployment) DeepCopy() *OdooDeployment {
	if in == nil {
		return nil
	}
	out := new(OdooDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDeploymentList) DeepCopyInto(out *OdooDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OdooDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDeploymentList.
func (in *OdooDeploymentList) DeepCopy() *OdooDeploymentList {
	if in == nil {
		return nil
	}
	out := new(OdooDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OdooDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDeploymentSpec) DeepCopyInto(out *OdooDeploymentSpec) {
	*out = *in
	if in.OdooCommand != nil {
		in, out := &in.OdooCommand, &out.OdooCommand
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	in.Database.DeepCopyInto(&out.Database)
	in.Config.DeepCopyInto(&out.Config)
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.OdooFilestore.DeepCopyInto(&out.OdooFilestore)
	in.Upgrade.DeepCopyInto(&out.Upgrade)
	in.Jobs.DeepCopyInto(&out.Jobs)
	in.Probes.DeepCopyInto(&out.Probes)
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDeploymentSpec.
func (in *OdooDeploymentSpec) DeepCopy() *OdooDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(OdooDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooDeploymentStatus) DeepCopyInto(out *OdooDeploymentStatus) {
	*out = *in
	in.Database.DeepCopyInto(&out.Database)
	if in.InitModulesInstalled != nil {
		in, out := &in.InitModulesInstalled, &out.InitModulesInstalled
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.CurrentInitJob.DeepCopyInto(&out.CurrentInitJob)
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooDeploymentStatus.
func (in *OdooDeploymentStatus) DeepCopy() *OdooDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(OdooDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooJobConfig) DeepCopyInto(out *OdooJobConfig) {
	*out = *in
	if in.ActiveDeadlineSeconds != nil {
		in, out := &in.ActiveDeadlineSeconds, &out.ActiveDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
	if in.BackoffLimit != nil {
		in, out := &in.BackoffLimit, &out.BackoffLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooJobConfig.
func (in *OdooJobConfig) DeepCopy() *OdooJobConfig {
	if in == nil {
		return nil
	}
	out := new(OdooJobConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooProbesConfig) DeepCopyInto(out *OdooProbesConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Startup != nil {
		in, out := &in.Startup, &out.Startup
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooProbesConfig.
func (in *OdooProbesConfig) DeepCopy() *OdooProbesConfig {
	if in == nil {
		return nil
	}
	out := new(OdooProbesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OdooUpgradeConfig) DeepCopyInto(out *OdooUpgradeConfig) {
	*out = *in
	if in.Modules != nil {
		in, out := &in.Modules, &out.Modules
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OnImageChange != nil {
		in, out := &in.OnImageChange, &out.OnImageChange
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OdooUpgradeConfig.
func (in *OdooUpgradeConfig) DeepCopy() *OdooUpgradeConfig {
	if in == nil {
		return nil
	}
	out := new(OdooUpgradeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PersistentVolumeClaimSpec) DeepCopyInto(out *PersistentVolumeClaimSpec) {
	*out = *in
	out.Size = in.Size.DeepCopy()
	if in.AccessModes != nil {
		in, out := &in.AccessModes, &out.AccessModes
		*out = make([]corev1.PersistentVolumeAccessMode, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PersistentVolumeClaimSpec.
func (in *PersistentVolumeClaimSpec) DeepCopy() *PersistentVolumeClaimSpec {
	if in == nil {
		return nil
	}
	out := new(PersistentVolumeClaimSpec)
	in.DeepCopyInto(out)
	return out
}
